#!/usr/bin/env sh
# Adapted from LukeSmithxyz/st.

menu="$(getmenu)"

for i in "$@"
do
    [ "$i" = "-y" ] || [ "$i" = "--yank" ] && willyank="1"
    [ "$i" = "-o" ] || [ "$i" = "--open" ] && willopen="1"
    [ "$i" = "-f" ] || [ "$i" = "--no-fuzzy" ] && alias menu="$menu -F"
done

[ -z "$willyank" ] && [ -z "$willopen" ] && exit

urlregex='(([a-zA-Z]+://|www\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@:$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)'

urls="$(tr -d '\n' | grep -aEo "$urlregex" | sed 's/^www./https:\/\/www\./g' | awk '!seen[$0]++')"

[ -z "$urls" ] && exit

[ "$willyank" = "1" ] && printf "%s\n" "$urls" | $menu -i -l 20 -p 'Copy which url?' | tr -d '\n' | xclip -sel clip

[ "$willopen" = "1" ] && {
    chosen="$(printf "%s\n" "$urls" | $menu -i -l 20 -p 'Follow which url?')"
    setsid --fork xdg-open "$chosen" > /dev/null 2>&1 &
}
